// =======================================
// ====== social_near_methods_const ======
export const social_near_methods_const = {
  storage_deposit: "storage_deposit",
  storage_withdraw: "storage_withdraw",
  storage_unregister: "storage_unregister",
  storage_balance_bounds: "storage_balance_bounds",
  storage_balance_of: "storage_balance_of",
  get_accounts: "get_accounts",
  get_account: "get_account",
  get_account_count: "get_account_count",
  get: "get",
  keys: "keys",
  set: "set",
  get_node_count: "get_node_count",
  get_nodes: "get_nodes",
  get_node: "get_node",
  grant_write_permission: "grant_write_permission",
  debug_get_permissions: "debug_get_permissions",
  is_write_permission_granted: "is_write_permission_granted",
  migrate_state: "migrate_state",
  genesis_init_node_count: "genesis_init_node_count",
  genesis_init_nodes: "genesis_init_nodes",
  genesis_init_accounts: "genesis_init_accounts",
  get_version: "get_version",
  get_shared_storage_pool: "get_shared_storage_pool",
  shared_storage_pool_deposit: "shared_storage_pool_deposit",
  share_storage: "share_storage",
  get_account_storage: "get_account_storage",
  new: "new",
  set_status: "set_status",
  get_status: "get_status",
} as const;
