// ==================================
// ====== poolv1_methods_const ======
export const poolv1_methods_const = {
  new: "new",
  ping: "ping",
  deposit: "deposit",
  deposit_and_stake: "deposit_and_stake",
  withdraw_all: "withdraw_all",
  withdraw: "withdraw",
  stake_all: "stake_all",
  stake: "stake",
  unstake_all: "unstake_all",
  unstake: "unstake",
  get_account_unstaked_balance: "get_account_unstaked_balance",
  get_account_staked_balance: "get_account_staked_balance",
  get_account_total_balance: "get_account_total_balance",
  is_account_unstaked_balance_available: "is_account_unstaked_balance_available",
  get_total_staked_balance: "get_total_staked_balance",
  get_owner_id: "get_owner_id",
  get_reward_fee_fraction: "get_reward_fee_fraction",
  get_staking_key: "get_staking_key",
  is_staking_paused: "is_staking_paused",
  get_account: "get_account",
  get_number_of_accounts: "get_number_of_accounts",
  get_accounts: "get_accounts",
  on_stake_action: "on_stake_action",
  update_staking_key: "update_staking_key",
  update_reward_fee_fraction: "update_reward_fee_fraction",
  vote: "vote",
  pause_staking: "pause_staking",
  resume_staking: "resume_staking",
} as const;