// ====================================
// ===== world_pumpopoly_methods_const =====
export const world_pumpopoly_methods_const = {
  view: [
    "metadata",
    "view_market",
    "view_lands",
    "view_players",
    "view_player",
    "view_player_count",
  ] as const,
  call: [
    "new",
    "award_land",
    "set_player_count",
    "set_player_invites",
    "set_player_invited_by",
    "set_player_balance",
    "elite_build",
    "on_elite_build",
    "build",
    "move_player",
    "elite_move",
    "on_elite_move",
    "helicopter",
    "taper",
    "end_sale",
    "sell_land",
    "exchequer_claim_bond",
    "on_exchequer_claim_bond",
    "exchequer_buy_land",
    "buy_land",
    "nft_on_transfer",
    "mint_nft",
    "claim_nft",
    "sync_nft",
    "on_buy_tokens",
    "on_nft_export",
    "on_mint_request_settlement",
    "ft_on_transfer",
  ] as const,
} as const;