// ====================================
// ===== world_pumpopoly_methods_const =====
export const world_pumpopoly_methods_const = {
  new: "new",
  award_land: "award_land",
  set_player_count: "set_player_count",
  set_player_invites: "set_player_invites",
  set_player_invited_by: "set_player_invited_by",
  set_player_balance: "set_player_balance",
  elite_build: "elite_build",
  on_elite_build: "on_elite_build",
  build: "build",
  move_player: "move_player",
  elite_move: "elite_move",
  on_elite_move: "on_elite_move",
  helicopter: "helicopter",
  taper: "taper",
  end_sale: "end_sale",
  sell_land: "sell_land",
  exchequer_claim_bond: "exchequer_claim_bond",
  on_exchequer_claim_bond: "on_exchequer_claim_bond",
  exchequer_buy_land: "exchequer_buy_land",
  buy_land: "buy_land",
  nft_on_transfer: "nft_on_transfer",
  mint_nft: "mint_nft",
  claim_nft: "claim_nft",
  sync_nft: "sync_nft",
  on_buy_tokens: "on_buy_tokens",
  on_nft_export: "on_nft_export",
  on_mint_request_settlement: "on_mint_request_settlement",
  ft_on_transfer: "ft_on_transfer",
  metadata: "metadata",
  view_market: "view_market",
  view_lands: "view_lands",
  view_players: "view_players",
  view_player: "view_player",
  view_player_count: "view_player_count",
} as const;