// ================================================
// ========== ref_exchange_methods_const ==========
export const ref_exchange_methods_const = {
  // Change methods (payable)
  new: "new",
  add_simple_pool: "add_simple_pool",
  add_stable_swap_pool: "add_stable_swap_pool",
  add_rated_swap_pool: "add_rated_swap_pool",
  add_degen_swap_pool: "add_degen_swap_pool",
  execute_actions_in_va: "execute_actions_in_va",
  execute_actions: "execute_actions",
  swap: "swap",
  swap_by_output: "swap_by_output",
  add_liquidity: "add_liquidity",
  add_stable_liquidity: "add_stable_liquidity",
  remove_liquidity: "remove_liquidity",
  remove_liquidity_by_tokens: "remove_liquidity_by_tokens",
  update_token_rate: "update_token_rate",
  update_degen_token_price: "update_degen_token_price",

  // Owner methods (payable)
  set_owner: "set_owner",
  retrieve_unmanaged_token: "retrieve_unmanaged_token",
  extend_guardians: "extend_guardians",
  remove_guardians: "remove_guardians",
  extend_auto_whitelisted_postfix: "extend_auto_whitelisted_postfix",
  remove_auto_whitelisted_postfix: "remove_auto_whitelisted_postfix",
  modify_boost_farm_id: "modify_boost_farm_id",
  modify_burrowland_id: "modify_burrowland_id",
  modify_wnear_id: "modify_wnear_id",
  change_state: "change_state",
  extend_whitelisted_tokens: "extend_whitelisted_tokens",
  remove_whitelisted_tokens: "remove_whitelisted_tokens",
  extend_frozenlist_tokens: "extend_frozenlist_tokens",
  remove_frozenlist_tokens: "remove_frozenlist_tokens",
  insert_referral: "insert_referral",
  update_referral: "update_referral",
  remove_referral: "remove_referral",
  modify_admin_fee: "modify_admin_fee",
  modify_total_fee: "modify_total_fee",
  remove_exchange_fee_liquidity: "remove_exchange_fee_liquidity",
  withdraw_owner_token: "withdraw_owner_token",

  // Storage management (payable)
  storage_deposit: "storage_deposit",
  storage_withdraw: "storage_withdraw",
  storage_unregister: "storage_unregister",
  storage_balance_of: "storage_balance_of",

  // Client echo limit methods (payable)
  extend_client_echo_token_id_whitelist: "extend_client_echo_token_id_whitelist",
  remove_client_echo_token_id_whitelist: "remove_client_echo_token_id_whitelist",
  extend_client_echo_sender_id_whitelist: "extend_client_echo_sender_id_whitelist",
  remove_client_echo_sender_id_whitelist: "remove_client_echo_sender_id_whitelist",
  extend_secure_sender_whitelist: "extend_secure_sender_whitelist",
  remove_secure_sender_whitelist: "remove_secure_sender_whitelist",

  // Donation methods (payable)
  donation_share: "donation_share",
  donation_token: "donation_token",

  // Lostfound methods (payable)
  claim_lostfound: "claim_lostfound",

  // View methods
  metadata: "metadata",
  get_guardians: "get_guardians",
  version: "version",
  get_number_of_pools: "get_number_of_pools",
  get_pools: "get_pools",
  get_pool: "get_pool",
  get_pool_by_ids: "get_pool_by_ids",
  get_pool_detail_infos: "get_pool_detail_infos",
  get_pool_detail_info: "get_pool_detail_info",
  get_pool_detail_info_by_ids: "get_pool_detail_info_by_ids",
  get_stable_pool: "get_stable_pool",
  get_rated_pool: "get_rated_pool",
  get_degen_pool: "get_degen_pool",
  get_pool_fee: "get_pool_fee",
  get_pool_volumes: "get_pool_volumes",
  get_pool_volumes_by_ids: "get_pool_volumes_by_ids",
  list_pool_volumes: "list_pool_volumes",
  get_pool_share_price: "get_pool_share_price",
  get_pool_shares: "get_pool_shares",
  get_pool_shares_batch: "get_pool_shares_batch",
  get_pool_total_shares: "get_pool_total_shares",
  get_deposits: "get_deposits",
  get_tokens_paged: "get_tokens_paged",
  get_account_basic_info: "get_account_basic_info",
  get_shadow_records: "get_shadow_records",
  get_deposit: "get_deposit",
  get_return: "get_return",
  get_return_by_output: "get_return_by_output",
  list_referrals: "list_referrals",
  get_frozenlist_tokens: "get_frozenlist_tokens",
  get_whitelisted_tokens: "get_whitelisted_tokens",
  get_user_whitelisted_tokens: "get_user_whitelisted_tokens",
  get_user_storage_state: "get_user_storage_state",
  predict_add_simple_liquidity: "predict_add_simple_liquidity",
  predict_add_stable_liquidity: "predict_add_stable_liquidity",
  predict_remove_liquidity: "predict_remove_liquidity",
  predict_remove_liquidity_by_tokens: "predict_remove_liquidity_by_tokens",
  list_rated_tokens: "list_rated_tokens",
  batch_get_degen_tokens: "batch_get_degen_tokens",
  list_degen_tokens: "list_degen_tokens",
  list_degen_oracle_configs: "list_degen_oracle_configs",
  predict_add_rated_liquidity: "predict_add_rated_liquidity",
  predict_add_degen_liquidity: "predict_add_degen_liquidity",
  predict_remove_rated_liquidity_by_tokens: "predict_remove_rated_liquidity_by_tokens",
  predict_remove_degen_liquidity_by_tokens: "predict_remove_degen_liquidity_by_tokens",
  get_rated_return: "get_rated_return",
  get_degen_return: "get_degen_return",
  predict_swap_actions: "predict_swap_actions",
  batch_predict_swap_actions: "batch_predict_swap_actions",
  predict_hot_zap: "predict_hot_zap",
  get_degen_pool_tvl: "get_degen_pool_tvl",
  get_pool_limit_by_pool_id: "get_pool_limit_by_pool_id",
  get_pool_limit_paged: "get_pool_limit_paged",
  batch_views: "batch_views",

  // Additional view methods
  get_client_echo_token_id_whitelist: "get_client_echo_token_id_whitelist",
  get_client_echo_sender_id_whitelist: "get_client_echo_sender_id_whitelist",
  get_secure_sender_whitelist: "get_secure_sender_whitelist",
} as const;
// ================================================
export const ref_mainnet_contractId_const = "v2.ref-finance.near"
export const ref_testnet_contractId_const = "ref-finance-101.testnet"
