// ===============================================
// ====== hos_voting_contract_methods_const ======
export const hos_voting_contract_methods_const = {
  accept_ownership: "accept_ownership",
  approve_proposal: "approve_proposal",
  contract_source_metadata: "contract_source_metadata",
  create_proposal: "create_proposal",
  get_approved_proposals: "get_approved_proposals",
  get_config: "get_config",
  get_num_approved_proposals: "get_num_approved_proposals",
  get_num_proposals: "get_num_proposals",
  get_proposal: "get_proposal",
  get_proposals: "get_proposals",
  get_version: "get_version",
  get_vote: "get_vote",
  is_paused: "is_paused",
  migrate_state: "migrate_state",
  new: "new",
  on_get_snapshot: "on_get_snapshot",
  pause: "pause",
  propose_new_owner_account_id: "propose_new_owner_account_id",
  reject_proposal: "reject_proposal",
  set_base_proposal_fee: "set_base_proposal_fee",
  set_guardians: "set_guardians",
  set_max_number_of_voting_options: "set_max_number_of_voting_options",
  set_reviewer_ids: "set_reviewer_ids",
  set_venear_account_id: "set_venear_account_id",
  set_voting_duration: "set_voting_duration",
  unpause: "unpause",
  vote: "vote",
} as const;